version: "3.8"
secrets:
  SFTP_TARGET:
    x-secrets:
      Name: ${SFTP_CLIENT_SECRET_NAME:-/sftp/client}
      VarName: SFTP_TARGET

volumes:
  shared:

services:
  s3-to-sftp:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${REGISTRY_URI:-public.ecr.aws/ews-network/}s3-to-sftp:${IMAGE_TAG:-latest}
    volumes:
      - shared:/shared
    deploy:
      labels:
        ecs.task.family: s3-to-sftp
    secrets:
      - SFTP_SECRET
